#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define SHIP_SIZE 16
#define SHIP_VELOCITY 0.05f
#define SHIP_THRUST_POWER 100.0f
#define SHIP_STEER_POWER 3.0f
#define MAX_SHIP_SPEED 200.0f

enum ASTEROID_SIZE { SMALL = 15, MEDIUM = 30, LARGE = 60 };
#define ASTEROID_MIN_VELOCITY 20.0f
#define ASTEROID_MAX_VELOCITY 70.0f
#define ASTEROID_SPAWN_MARGIN 40
#define ASTEROID_SAFE_SPAWN_RADIUS 300
#define MAX_ASTEROID_NUMBER 128

#define BULLET_RADIUS 2.0f
#define BULLET_SPEED 400.0f
#define BULLET_COOLDOWN 0.25f
#define MAX_BULLET_NUMBER 32

#define WAVE_MULTIPLIER 3

#define WINDOW_TEXT_MARGIN 20
#define FONT_SIZE 20

#define GAMEOVER_FONT_SIZE 50
#define GAMEOVER_COOLDOWN 1.0f

#endif